name: measurement_app
description: 3D Measurement App with Auto-Capture

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP client
  http: ^1.1.0
  dio: ^5.3.3
  
  # Camera
  camera: ^0.10.5+5
  
  # Image handling
  image: ^4.1.3
  path_provider: ^2.1.1
  
  # Sensors (for guidance)
  sensors_plus: ^3.1.0
  
  # State management
  provider: ^6.0.5
  
  # Permissions
  permission_handler: ^11.0.1
  
  # UI
  flutter_spinkit: ^5.2.0
  percent_indicator: ^4.2.3
  
  # Utils
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

